const CONTACT_EMAIL = "victoriacheeng1122@gmail.com";
const contactMailto = `<a class="inline-link" href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a>`;

const copy = {
  home: {
    zh: {
      title: "複利計算器-財務自由實現工具｜產品說明",
      description: "複利計算器-財務自由實現工具是一款整合通膨、財務自由、借貸壓力與退休規劃的長期財務試算工具。",
      brandName: "複利計算器-財務自由實現工具",
      navPrivacy: "隱私權政策",
      navCopyright: "版權聲明",
      navTerms: "使用條款",
      navContact: "聯絡作者",
      heroEyebrow: "財務自由實現工具",
      heroTitle: "把通膨、財務自由、借貸壓力與退休規劃整理進同一套工具裡",
      heroCopy: "複利計算器-財務自由實現工具以長期規劃為核心，整合投資複利、通膨換算、財務自由、退休準備與貸款壓力判讀，幫你用更清楚的數字理解自己的規劃方向。",
      highlightOne: "通膨與實質報酬",
      highlightTwo: "FIRE 與退休規劃",
      highlightThree: "貸款壓力判讀",
      ctaPrivacy: "查看隱私權政策",
      ctaTerms: "查看使用條款",
      asideEyebrow: "平台範圍",
      asideTitle: "核心規劃範圍",
      asideMetricOneLabel: "投資",
      asideMetricOneValue: "複利成長",
      asideMetricTwoLabel: "FIRE",
      asideMetricTwoValue: "情境規劃",
      asideMetricThreeLabel: "退休",
      asideMetricThreeValue: "提領試算",
      asideMetricFourLabel: "貸款",
      asideMetricFourValue: "風險比較",
      asideCopy: "適合想把投資成長、財務自由、退休目標與借貸壓力放在同一套假設下比較的人。",
      featureEyebrow: "產品介紹",
      featureTitle: "一個把長期財務規劃講清楚的工具",
      featureCopy: "複利計算器-財務自由實現工具提供投資複利、通膨換算、FIRE 規劃、退休試算與貸款分析，幫你更快看懂重要數字、比較不同情境，整理出更適合自己的規劃方向。",
      featureItemOne: "同時整理名義報酬、實質報酬與購買力變化",
      featureItemTwo: "用圖表與摘要卡快速判讀 FIRE、退休與借貸壓力",
      featureItemThree: "透過專業版比較情境、匯出報告，整理更完整的規劃結果",
      metricOneLabel: "主要功能",
      metricOneValue: "通膨、FIRE、退休、貸款",
      metricTwoLabel: "資料處理",
      metricTwoValue: "以裝置本機計算為主",
      metricThreeLabel: "訂閱與付款",
      metricThreeValue: "透過 Apple 訂閱與付款機制管理",
      premiumEyebrow: "專業版",
      premiumTitle: "進階比較、摘要整理與更深入的規劃分析",
      premiumCopy: "專業版適合需要反覆比較投資、FIRE、退休與貸款方案的人，幫你更快整理情境差異、風險提示與報告摘要。",
      premiumTagOne: "情境比較",
      premiumTagTwo: "壓力測試",
      premiumTagThree: "摘要報告",
      linksEyebrow: "支援與法務",
      linksPrivacy: "隱私權政策",
      linksCopyright: "版權聲明",
      linksTerms: "使用條款",
      linksContact: "聯絡作者",
      linksPrivacyCopy: "了解 App 如何處理你的資料與裝置上的設定。",
      linksCopyrightCopy: "查看內容使用方式、版權歸屬與授權說明。",
      linksTermsCopy: "快速了解服務範圍、責任界線，以及專業版訂閱的基本條款。",
      linksContactCopy: "需要支援、回報問題或詢問產品內容時，可直接透過 email 聯繫。",
      noteEyebrow: "合規聲明",
      noteCopy: "本網站提供的是產品與使用資訊，協助你了解複利計算器-財務自由實現工具如何運作，以及專業版訂閱如何由 Apple 管理。網站內容不構成投資、保險、貸款或法律建議。",
      footerCopy: "© 2026 複利計算器-財務自由實現工具. All rights reserved."
    },
    en: {
      title: "Investment Growth | Product Overview",
      description: "Investment Growth is a long-term financial planning tool that brings inflation, financial independence, debt pressure, and retirement planning into one experience.",
      brandName: "Investment Growth",
      navPrivacy: "Privacy Policy",
      navCopyright: "Copyright Notice",
      navTerms: "Terms of Use",
      navContact: "Contact",
      heroEyebrow: "財務自由實現工具",
      heroTitle: "One place to review inflation, financial independence, debt pressure, and retirement planning",
      heroCopy: "Investment Growth brings compound growth, inflation-adjusted returns, FIRE planning, retirement modeling, and debt pressure review into one planning experience, helping users make clearer long-term decisions.",
      highlightOne: "Inflation-aware",
      highlightTwo: "FIRE and retirement",
      highlightThree: "Debt pressure review",
      ctaPrivacy: "View Privacy Policy",
      ctaTerms: "View Terms of Use",
      asideEyebrow: "Platform Scope",
      asideTitle: "Core Planning Coverage",
      asideMetricOneLabel: "Investment",
      asideMetricOneValue: "Compound Growth",
      asideMetricTwoLabel: "FIRE",
      asideMetricTwoValue: "Scenario Planning",
      asideMetricThreeLabel: "Retirement",
      asideMetricThreeValue: "Withdrawal Modeling",
      asideMetricFourLabel: "Loans",
      asideMetricFourValue: "Risk Comparison",
      asideCopy: "Designed for people who want to compare growth, retirement, and debt decisions under one consistent planning framework.",
      featureEyebrow: "Product Overview",
      featureTitle: "A clearer way to plan long-term finances and purchasing power",
      featureCopy: "Investment Growth includes tools for compound growth, inflation-adjusted returns, FIRE planning, retirement planning, and loan analysis, helping you compare scenarios and understand the numbers that matter.",
      featureItemOne: "A consistent input model across investing, retirement, and loan planning",
      featureItemTwo: "Clear visual outputs that help surface the numbers that matter most",
      featureItemThree: "Premium tools for comparing scenarios and evaluating stress cases",
      metricOneLabel: "Core Areas",
      metricOneValue: "Inflation, FIRE, Retirement, Loans",
      metricTwoLabel: "Data Handling",
      metricTwoValue: "Calculated mainly on your device",
      metricThreeLabel: "Subscriptions & Billing",
      metricThreeValue: "Managed through Apple billing and subscriptions",
      premiumEyebrow: "Premium",
      premiumTitle: "Deeper comparison, summary reporting, and advanced planning analysis",
      premiumCopy: "Premium is designed for users who repeatedly compare investing, FIRE, retirement, and loan scenarios and want a faster way to organize differences and key observations.",
      premiumTagOne: "Scenario Comparison",
      premiumTagTwo: "Stress Testing",
      premiumTagThree: "Summary Reports",
      linksEyebrow: "Support & Legal",
      linksPrivacy: "Privacy Policy",
      linksCopyright: "Copyright Notice",
      linksTerms: "Terms of Use",
      linksContact: "Contact",
      linksPrivacyCopy: "See how the app handles your data and on-device settings.",
      linksCopyrightCopy: "Review ownership, permitted use, and licensing notes.",
      linksTermsCopy: "Understand service scope, responsibilities, and the basic terms for Premium subscriptions.",
      linksContactCopy: "Reach out by email for product support, issue reports, or general questions.",
      noteEyebrow: "Compliance Notice",
      noteCopy: "This website provides product and usage information to help you understand how Investment Growth works and how Premium subscriptions are managed through Apple. It does not constitute investment, insurance, lending, or legal advice.",
      footerCopy: "© 2026 Investment Growth. All rights reserved."
    }
  },
  privacy: {
    zh: {
      title: "複利計算器-財務自由實現工具｜隱私權政策",
      description: "了解複利計算器-財務自由實現工具如何處理你的資料、裝置上的設定，以及 Apple 訂閱相關流程。",
      brandName: "複利計算器-財務自由實現工具",
      navPrivacy: "隱私權政策",
      navCopyright: "版權聲明",
      navTerms: "使用條款",
      navContact: "聯絡作者",
      heroEyebrow: "Privacy",
      heroTitle: "隱私權政策",
      heroIntro: "這份說明整理了複利計算器-財務自由實現工具如何處理你的輸入資料、裝置上的偏好設定，以及 Apple 訂閱相關流程。",
      heroDate: "最後更新日期：2026 年 4 月 10 日",
      backHome: "回首頁",
      goTerms: "前往使用條款",
      goContact: "聯絡作者",
      asideEyebrow: "Privacy Summary",
      asideTitle: "以裝置端試算為主",
      asideMetricOneLabel: "主要處理",
      asideMetricOneValue: "試算輸入與設定",
      asideMetricTwoLabel: "付款",
      asideMetricTwoValue: "由 Apple 管理",
      asideMetricThreeLabel: "分享",
      asideMetricThreeValue: "由你自行決定",
      asideCopy: "這一頁的重點是讓你快速知道：資料主要留在裝置上，訂閱付款由 Apple 處理，分享行為由你控制。",
      section1Title: "1. 政策概要",
      section1Copy: "複利計算器-財務自由實現工具重視你的個人隱私。本 App 主要在你的裝置上完成財務試算與情境規劃。除 Apple 訂閱與系統服務所需流程外，開發者不會主動蒐集、上傳、出售或建立你的個人財務資料庫。",
      section2Title: "2. App 可能處理的資料",
      section2Intro: "為了完成試算、儲存情境與保留設定，App 可能在你的裝置上處理以下資訊：",
      section2Item1: "投資、退休、貸款、財務自由相關的試算輸入數值",
      section2Item2: "你選擇儲存的情境資料",
      section2Item3: "語言、主題與預設假設等本機偏好設定",
      section2Item4: "Apple 提供的訂閱狀態資訊，用於判斷專業版功能是否已啟用",
      section3Title: "3. 資料如何使用",
      section3Item1: "用於完成投資、FIRE、退休與貸款相關試算",
      section3Item2: "用於保留你在裝置上的偏好設定與已儲存情境",
      section3Item3: "用於顯示專業版功能狀態，以及處理恢復購買結果",
      section3Copy: "除 Apple 訂閱流程與 iOS 系統服務所需機制外，開發者不會為了行銷、分析或追蹤目的，主動將你的試算內容上傳到自建伺服器，也不會將這些資料出售或分享給第三方。",
      section4Title: "4. 訂閱與付款",
      section4Copy: "複利計算器-財務自由實現工具的專業版訂閱由 Apple 提供並管理。確認購買後，款項會透過你的 Apple ID 帳戶收取；續訂、取消與退款規則，依 Apple 的 App Store 與訂閱服務條款處理。開發者不會直接持有你的信用卡或完整付款資訊。",
      section5Title: "5. 分享功能",
      section5Copy: "若你使用 App 內的摘要分享功能，分享內容會透過 iOS 系統分享流程交由你指定的 App 或服務。是否傳送、傳送給誰，以及後續如何保存，均由你自行決定。",
      section6Title: "6. 資料保存",
      section6Copy: "你在 App 內輸入或儲存的多數資料，原則上保留於本機裝置與系統層級儲存機制中。若你刪除 App，相關本機資料通常也會一併移除；實際情況仍取決於 Apple 平台與你的備份設定。",
      section7Title: "7. 第三方服務",
      section7Intro: "本 App 可能依賴以下平台服務：",
      section7Item1: "Apple App Store：提供下載、更新與訂閱管理",
      section7Item2: "Apple StoreKit：處理 App 內訂閱購買與權限驗證",
      section7Item3: "iOS System Share Sheet：處理使用者主動發起的摘要分享",
      section8Title: "8. 聯絡方式",
      section8Copy: `如果你對本政策有任何疑問，或想回報與資料處理相關的問題，請來信至 ${contactMailto}，我們會盡快回覆你。`,
      footerCopy: "© 2026 複利計算器-財務自由實現工具. All rights reserved."
    },
    en: {
      title: "Investment Growth | Privacy Policy",
      description: "Learn how Investment Growth handles your data, on-device settings, and Apple-managed subscription flows.",
      brandName: "Investment Growth",
      navPrivacy: "Privacy Policy",
      navCopyright: "Copyright Notice",
      navTerms: "Terms of Use",
      navContact: "Contact",
      heroEyebrow: "Privacy",
      heroTitle: "Privacy Policy",
      heroIntro: "This page explains how Investment Growth handles your inputs, on-device preferences, and Apple-managed subscription flows.",
      heroDate: "Last updated: April 10, 2026",
      backHome: "Back to Home",
      goTerms: "Go to Terms of Use",
      goContact: "Contact",
      asideEyebrow: "Privacy Summary",
      asideTitle: "Designed around on-device planning",
      asideMetricOneLabel: "Main data",
      asideMetricOneValue: "Inputs and saved settings",
      asideMetricTwoLabel: "Billing",
      asideMetricTwoValue: "Managed by Apple",
      asideMetricThreeLabel: "Sharing",
      asideMetricThreeValue: "User-controlled",
      asideCopy: "The quick version: most planning data stays on your device, subscription billing is handled by Apple, and sharing only happens when you choose it.",
      section1Title: "1. Overview",
      section1Copy: "Investment Growth respects your privacy. The app is designed to perform financial calculations and scenario planning mainly on your device. Apart from Apple subscription and system-service flows, the developer does not actively collect, upload, sell, or maintain a centralized database of your personal financial data.",
      section2Title: "2. Data the App May Process",
      section2Intro: "To complete calculations, save scenarios, and preserve preferences, the app may process the following information on your device:",
      section2Item1: "Calculation inputs related to investing, retirement, loans, and FIRE planning",
      section2Item2: "Scenario data you choose to save",
      section2Item3: "On-device preferences such as language, theme, and default assumptions",
      section2Item4: "Subscription status information provided by Apple to determine whether Pro features are active",
      section3Title: "3. How Data Is Used",
      section3Item1: "To run investing, FIRE, retirement, and loan calculations",
      section3Item2: "To preserve your preferences and saved scenarios on your device",
      section3Item3: "To display Pro access status and handle restore-purchase results",
      section3Copy: "Other than system services required for Apple subscription flows and iOS sharing features, the developer does not upload your calculation content to a custom backend for analytics or marketing, and does not sell or share it with third parties.",
      section4Title: "4. Subscriptions and Payments",
      section4Copy: "Premium subscriptions for Investment Growth are provided and managed by Apple. After purchase confirmation, payment is charged to your Apple ID account. Renewals, cancellations, and refunds are handled under Apple App Store and subscription terms. The developer does not directly store your credit card details or full billing information.",
      section5Title: "5. Sharing Features",
      section5Copy: "If you use the in-app summary sharing feature, the content is passed through the iOS system sharing flow to the app or service you choose. Whether it is sent, where it is sent, and how it is later stored are decisions under your control.",
      section6Title: "6. Data Retention",
      section6Copy: "Most information you enter or save in the app stays on your device using system-level storage. If you remove the app, that local data is typically removed as well, although the exact behavior may still depend on Apple platform behavior and your backup settings.",
      section7Title: "7. Third-Party Services",
      section7Intro: "The app may rely on the following platform services:",
      section7Item1: "Apple App Store: for downloads, updates, and subscription management",
      section7Item2: "Apple StoreKit: for in-app subscription purchases and entitlement validation",
      section7Item3: "iOS System Share Sheet: for user-initiated summary sharing",
      section8Title: "8. Contact",
      section8Copy: `If you have any questions about this policy, or would like to report a data-related concern, please contact us at ${contactMailto}.`,
      footerCopy: "© 2026 Investment Growth. All rights reserved."
    }
  },
  copyright: {
    zh: {
      title: "複利計算器-財務自由實現工具｜內容使用與版權說明",
      description: "了解複利計算器-財務自由實現工具的內容如何使用、哪些內容受保護，以及相關版權說明。",
      brandName: "複利計算器-財務自由實現工具",
      navPrivacy: "隱私權政策",
      navCopyright: "版權聲明",
      navTerms: "使用條款",
      navContact: "聯絡作者",
      heroEyebrow: "Copyright",
      heroTitle: "內容使用與版權說明",
      heroDate: "最後更新日期：2026 年 4 月 10 日",
      backHome: "回首頁",
      goTerms: "前往使用條款",
      section1Title: "1. 這些內容屬於誰",
      section1Copy: "複利計算器-財務自由實現工具 App、本網站、介面設計、文案、圖像、圖表呈現、程式碼結構與相關內容，除另有標示外，相關著作權與其他智慧財產權原則上都屬於開發者所有。",
      section2Title: "2. 你可以怎麼使用這些內容",
      section2Intro: "如果沒有另外取得明確授權，以下內容不適合被重製、改作、轉傳、再授權或用於商業用途：",
      section2Item1: "App 內畫面設計與品牌視覺",
      section2Item2: "本網站內容與版面設計",
      section2Item3: "試算結果呈現方式、報告樣式與說明文案",
      section2Item4: "應用程式圖示與品牌識別元素",
      section3Title: "3. 第三方服務與權利",
      section3Copy: "本 App 可能使用 Apple 提供的系統框架、介面元件或訂閱服務。相關名稱、商標與服務權利，分別屬於各自權利人所有。",
      section4Title: "4. 內容性質說明",
      section4Copy: "複利計算器-財務自由實現工具提供的是試算、整理與比較工具，協助你理解不同情境下的數字變化。網站與 App 的內容主要是一般資訊與產品使用說明，不構成投資、保險、貸款、會計或法律意見，也不保證任何報酬、核貸結果或保單給付。",
      section5Title: "5. 如果你有問題",
      section5Copy: `如果你對內容使用方式有疑問，或認為本網站與 App 的內容涉及權利問題，請來信至 ${contactMailto}，我們會盡快協助你。`,
      footerCopy: "© 2026 複利計算器-財務自由實現工具. All rights reserved."
    },
    en: {
      title: "Investment Growth | Content Use and Copyright",
      description: "Learn how Investment Growth content may be used, what is protected, and how copyright is handled.",
      brandName: "Investment Growth",
      navPrivacy: "Privacy Policy",
      navCopyright: "Copyright Notice",
      navTerms: "Terms of Use",
      navContact: "Contact",
      heroEyebrow: "Copyright",
      heroTitle: "Content Use and Copyright",
      heroDate: "Last updated: April 10, 2026",
      backHome: "Back to Home",
      goTerms: "Go to Terms of Use",
      section1Title: "1. Who Owns This Content",
      section1Copy: "Unless otherwise stated, the app, website, interface design, copy, graphics, chart presentation, code structure, and related materials of Investment Growth are protected by copyright and other intellectual property rights owned by the developer.",
      section2Title: "2. How This Content May Be Used",
      section2Intro: "Unless you have explicit permission, the following materials should not be copied, adapted, redistributed, relicensed, or used commercially:",
      section2Item1: "In-app interface design and brand visuals",
      section2Item2: "Website content and page design",
      section2Item3: "How calculation results, reports, and explanatory copy are presented",
      section2Item4: "The app icon and brand identity elements",
      section3Title: "3. Third-Party Services and Rights",
      section3Copy: "The app may rely on Apple-provided frameworks, interface components, or subscription services. Related names, trademarks, and service rights belong to their respective owners.",
      section4Title: "4. What This Content Is For",
      section4Copy: "Investment Growth provides tools for calculation, organization, and comparison to help users understand how figures may change across different scenarios. The app and website content is intended as general information and product guidance, and does not guarantee investment returns, loan approval outcomes, insurance payouts, or retirement planning results.",
      section5Title: "5. If You Have a Question",
      section5Copy: `If you have questions about how the content may be used, or believe any part of the app or website affects your rights, please contact us at ${contactMailto}.`,
      footerCopy: "© 2026 Investment Growth. All rights reserved."
    }
  },
  terms: {
    zh: {
      title: "複利計算器-財務自由實現工具｜使用條款",
      description: "了解複利計算器-財務自由實現工具的使用條款與服務範圍。",
      brandName: "複利計算器-財務自由實現工具",
      navPrivacy: "隱私權政策",
      navCopyright: "版權聲明",
      navTerms: "使用條款",
      navContact: "聯絡作者",
      heroEyebrow: "Terms",
      heroTitle: "使用條款",
      heroDate: "最後更新日期：2026 年 4 月 10 日",
      backHome: "回首頁",
      goPrivacy: "前往隱私權政策",
      section1Title: "1. 條款適用範圍",
      section1Copy: "歡迎使用複利計算器-財務自由實現工具。當你下載、安裝或使用本 App 與本網站內容時，即表示你同意遵守本使用條款。若你不同意本條款，請停止使用相關服務。",
      section2Title: "2. 服務內容",
      section2Copy: "複利計算器-財務自由實現工具提供投資、FIRE、退休與貸款等財務試算工具，目的在於協助使用者整理資訊與理解不同情境下的數字變化。App 提供的是試算與比較工具，不代表任何保證收益、核貸結果或保單給付承諾。",
      section3Title: "3. 使用者責任",
      section3Item1: "你應自行評估輸入資料的正確性與完整性",
      section3Item2: "你應自行判斷試算結果是否適合用於真實財務決策",
      section3Item3: "你不得利用本 App 或網站從事違法、侵權或濫用行為",
      section4Title: "4. 專業版與訂閱",
      section4Copy: "部分功能屬於專業版內容，需透過 Apple 提供的自動續訂訂閱機制啟用。訂閱方案、期間與價格會在 App 內購買頁與 Apple 購買確認畫面中顯示。",
      section4Item1: "確認購買後，款項會透過你的 Apple ID 帳戶收取。",
      section4Item2: "訂閱會自動續訂，除非你在目前訂閱期間結束前至少 24 小時取消。",
      section4Item3: "你可以在 Apple ID 帳戶設定中管理或取消訂閱。",
      section4Item4: "續訂、取消與退款規則依 Apple App Store 與訂閱條款辦理。",
      section5Title: "5. 免責聲明",
      section5Copy: "本 App 與本網站內容僅供一般資訊、教育與個人規劃參考，不構成投資、保險、貸款、稅務、會計或法律意見。因使用本工具而採取的任何財務決策，風險與責任均由使用者自行承擔。",
      section6Title: "6. 服務調整與更新",
      section6Copy: "開發者有權依產品需求、法規變動或平台要求，隨時調整、更新、暫停或終止部分功能與說明內容，並於合理範圍內更新相關條款。",
      section7Title: "7. 聯絡方式",
      section7Copy: `如果你對本使用條款有任何疑問，或想進一步了解 App 的使用方式，請來信至 ${contactMailto}，我們會盡快回覆你。`,
      footerCopy: "© 2026 複利計算器-財務自由實現工具. All rights reserved."
    },
    en: {
      title: "Investment Growth | Terms of Use",
      description: "Learn about the terms of use and service scope for Investment Growth.",
      brandName: "Investment Growth",
      navPrivacy: "Privacy Policy",
      navCopyright: "Copyright Notice",
      navTerms: "Terms of Use",
      navContact: "Contact",
      heroEyebrow: "Terms",
      heroTitle: "Terms of Use",
      heroDate: "Last updated: April 10, 2026",
      backHome: "Back to Home",
      goPrivacy: "Go to Privacy Policy",
      section1Title: "1. Scope of the Terms",
      section1Copy: "Welcome to Investment Growth. By downloading, installing, or using the app or this website, you agree to follow these Terms of Use. If you do not agree, please discontinue use of the related services.",
      section2Title: "2. What the Service Provides",
      section2Copy: "Investment Growth offers financial calculation tools for investing, FIRE planning, retirement planning, and loan analysis. The purpose is to help users organize information and understand how figures may change across different scenarios. The app is a calculation and comparison tool, and does not represent guaranteed returns, loan approvals, or policy payout commitments.",
      section3Title: "3. User Responsibilities",
      section3Item1: "You are responsible for evaluating the accuracy and completeness of the values you enter",
      section3Item2: "You are responsible for deciding whether calculation results are suitable for real financial decisions",
      section3Item3: "You may not use the app or website for unlawful, infringing, or abusive activity",
      section4Title: "4. Pro Features and Subscriptions",
      section4Copy: "Some features are available only in the Premium version and are unlocked through Apple’s auto-renewable subscription system. Subscription plans, periods, and prices are shown on the in-app purchase page and Apple purchase confirmation sheet.",
      section4Item1: "After purchase confirmation, payment is charged to your Apple ID account.",
      section4Item2: "The subscription renews automatically unless it is canceled at least 24 hours before the end of the current period.",
      section4Item3: "You can manage or cancel your subscription in your Apple ID account settings.",
      section4Item4: "Renewals, cancellations, and refunds are handled under Apple App Store and subscription terms.",
      section5Title: "5. Disclaimer",
      section5Copy: "The app and this website are provided for general information, education, and personal planning purposes only. They do not constitute investment, insurance, lending, tax, accounting, or legal advice. Any financial decisions made using this tool are taken at your own risk and responsibility.",
      section6Title: "6. Service Changes and Updates",
      section6Copy: "The developer may adjust, update, suspend, or discontinue parts of the service or related explanations at any time in response to product needs, legal changes, or platform requirements, and may update these terms within a reasonable scope.",
      section7Title: "7. Contact",
      section7Copy: `If you have any questions about these Terms of Use, or would like to better understand how the app is intended to be used, please contact us at ${contactMailto}.`,
      footerCopy: "© 2026 Investment Growth. All rights reserved."
    }
  },
  contact: {
    zh: {
      title: "複利計算器-財務自由實現工具｜聯絡作者",
      description: "若你需要產品支援、回報問題或詢問複利計算器-財務自由實現工具的使用方式，可透過 email 聯絡作者。",
      brandName: "複利計算器-財務自由實現工具",
      navPrivacy: "隱私權政策",
      navCopyright: "版權聲明",
      navTerms: "使用條款",
      navContact: "聯絡作者",
      heroEyebrow: "Contact",
      heroTitle: "聯絡作者",
      heroIntro: "如果你對複利計算器-財務自由實現工具的使用方式、訂閱內容、法務頁說明或資料處理方式有疑問，可以直接來信。",
      heroDate: "回覆時間通常為 3 至 5 個工作天",
      ctaEmail: "寄送 email",
      backHome: "回首頁",
      asideEyebrow: "Support Scope",
      asideTitle: "適合聯絡的內容",
      asideMetricOneLabel: "產品支援",
      asideMetricOneValue: "功能與操作問題",
      asideMetricTwoLabel: "訂閱相關",
      asideMetricTwoValue: "權限與使用流程",
      asideMetricThreeLabel: "法務頁面",
      asideMetricThreeValue: "內容與資料說明",
      asideCopy: "若是 Apple 帳單、退款或取消訂閱，仍需以 Apple ID 訂閱管理與 App Store 規則為準。",
      section1Title: "1. 聯絡方式",
      section1Copy: `你可以透過 ${contactMailto} 與我們聯繫。若方便，也可以在信中附上裝置型號、iOS 版本與問題描述，會更有助於我們判斷狀況。`,
      section2Title: "2. 適合詢問的內容",
      section2Item1: "功能如何使用，或哪個工具適合你的規劃情境",
      section2Item2: "Premium 權限、報告輸出或提醒設定相關問題",
      section2Item3: "網站法務內容、隱私說明或聯絡方式更新",
      section3Title: "3. Apple 訂閱與帳單說明",
      section3Copy: "訂閱購買、續訂、取消與退款，均由 Apple 管理。如果問題與帳單、退款或 Apple ID 訂閱設定有關，建議優先透過 Apple 的訂閱管理頁面處理。",
      section4Title: "4. 回覆方式",
      section4Copy: "我們會盡量在合理時間內回覆，但實際速度仍會依來信量與問題性質而有所不同。若問題需要較多資訊確認，可能會再請你補充裝置環境或操作步驟。",
      footerCopy: "© 2026 複利計算器-財務自由實現工具. All rights reserved."
    },
    en: {
      title: "Investment Growth | Contact the Developer",
      description: "For product support, issue reports, or questions about Investment Growth, you can reach the developer by email.",
      brandName: "Investment Growth",
      navPrivacy: "Privacy Policy",
      navCopyright: "Copyright Notice",
      navTerms: "Terms of Use",
      navContact: "Contact",
      heroEyebrow: "Contact",
      heroTitle: "Contact the Developer",
      heroIntro: "If you have questions about product usage, subscriptions, legal pages, or data handling, feel free to contact us and we will reply as soon as we reasonably can.",
      heroDate: "Typical response time: 3 to 5 business days",
      ctaEmail: "Send email",
      backHome: "Back to Home",
      asideEyebrow: "Support Scope",
      asideTitle: "Topics that fit best here",
      asideMetricOneLabel: "Product support",
      asideMetricOneValue: "Feature and usage questions",
      asideMetricTwoLabel: "Subscriptions",
      asideMetricTwoValue: "Entitlements and access flow",
      asideMetricThreeLabel: "Legal pages",
      asideMetricThreeValue: "Content and policy explanations",
      asideCopy: "For Apple billing, refunds, or cancellation, Apple ID subscription management and App Store rules remain the source of record.",
      section1Title: "1. How to reach us",
      section1Copy: `You can contact us at ${contactMailto}. If helpful, include your device model, iOS version, and a short description of the issue so we can understand the situation faster.`,
      section2Title: "2. Good topics to ask about",
      section2Item1: "How a feature works, or which planning tool best fits your situation",
      section2Item2: "Premium access, report exports, or reminder settings",
      section2Item3: "Website legal content, privacy explanations, or contact details",
      section3Title: "3. Apple billing and subscriptions",
      section3Copy: "Purchases, renewals, cancellations, and refunds are managed by Apple. If your question is specifically about billing, refunds, or Apple ID subscription settings, Apple’s subscription management pages are the best place to start.",
      section4Title: "4. How replies work",
      section4Copy: "We aim to respond within a reasonable timeframe, though actual timing may vary depending on message volume and the nature of the question. If more detail is needed, we may ask for extra context about your device or the steps you took.",
      footerCopy: "© 2026 Investment Growth. All rights reserved."
    }
  }
};

const page = document.documentElement.dataset.page;
const metaDescription = document.querySelector('meta[name="description"]');
const langButtons = Array.from(document.querySelectorAll(".lang-btn"));
const translatableNodes = Array.from(document.querySelectorAll("[data-i18n]"));
const savedLang = localStorage.getItem("compound-site-lang");
const defaultLang = savedLang === "en" ? "en" : "zh";
const pageCopy = copy[page];

function setNodeCopy(node, value) {
  if (node.dataset.i18nHtml === "true") {
    node.innerHTML = value;
    return;
  }
  node.textContent = value;
}

function applyLanguage(lang) {
  const localizedCopy = pageCopy?.[lang];
  if (!localizedCopy) return;

  document.documentElement.lang = lang === "zh" ? "zh-Hant" : "en";
  document.title = localizedCopy.title;
  if (metaDescription) {
    metaDescription.setAttribute("content", localizedCopy.description);
  }

  translatableNodes.forEach((node) => {
    const key = node.dataset.i18n;
    if (!(key in localizedCopy)) return;
    setNodeCopy(node, localizedCopy[key]);
  });

  langButtons.forEach((btn) => {
    const isActive = btn.dataset.lang === lang;
    btn.classList.toggle("active", isActive);
    btn.setAttribute("aria-pressed", isActive ? "true" : "false");
  });

  localStorage.setItem("compound-site-lang", lang);
}

langButtons.forEach((btn) => {
  btn.addEventListener("click", () => applyLanguage(btn.dataset.lang));
});

if (pageCopy) {
  applyLanguage(defaultLang);
}
